### ISSUE TITLE
I created a SPI class for java and C++ that you folks might be interested in.

### ISSUE THREAD

**Issue by croadfeldt** [BHSRobotix/Steamworks2017#5]
Started with your I2C code, changed up some of the behavior of the objects themselves and have plans to add in code to config the pixy from the class. Also if possible, looking to add in a visualizer for the SmartDashboard.

https://github.com/croadfeldt/wpilib_pixy_spi_c-plus-plus
https://github.com/croadfeldt/wpilib_pixy_spi_java

**Comment by loafdog** [comment]
👍 
glad our code helped you along in your project.  We have plans to refactor and cleanup much of the pixy/vision code.  Leaving it alone for now until competitions are over.  There is code with more comments in a branch called 'comments' if you would like more info about pieces of code.  We haven't merged it to master yet.

**Comment by croadfeldt** [comment]
Right on, thanks!

There's a lot of crossover here, interested in merging it altogether and submitting it to wpilib github?

If so, it would trivial to carve up the class files into i2c, spi and pixy comms.

Chris

**Comment by croadfeldt** [comment]
Closing this as it's not an issue.
